import React from "react"

const NotStarted = ({ user, details }) => {
  const { role } = user
  const { title, agenda = "" } = details

  /*
    XXX TODO:
    Instead of comparing role directly to a string "host" the values for
    roles should be defined as constants in some file and imported into
    Activity.
    */
  return (
    <div className="jumbotron">
      <h1 className="display-4">
        {title === "" ? <span className="text-secondary">[Title]</span> : title}
      </h1>
      <p className="pt-3">
        {/* XXX TODO: Move hard coded instructions from here to activityListing or
        some other location. */}
        Zync Brainstorming follows a three step format - ideate, review and
        converge.
      </p>
      <h5>Ideate</h5>
      <p>
        Generate as many ideas as possible. You may tag the ideas with keywords
        that can later be used to group, search or filter ideas.
      </p>
      <h5>Review</h5>
      <p>
        You'll get a chance to look at the ideas generated by other attendees.
        You may choose to add your suggestions on how you would build on these
        ideas. Other users may have added their suggestions to some of these
        ideas.
      </p>
      <h5>Converge</h5>
      <p>
        The moderator will pick each idea and will discuss it with the group to
        triage and prioritize the ideas. Triaged ideas can be assigned next
        actions and assigned to specific team members.
      </p>
      <hr className="mb-4 mt-3 mr-5" />
      <div
        className="container-flex bg-light p-3 mb-3"
        style={{ width: "75%" }}
      >
        <h2>Agenda</h2>
        <p>
          {agenda === "" ? (
            <span className="text-secondary">[Agenda]</span>
          ) : (
            agenda
          )}
        </p>
      </div>
      {role !== "host" && (
        <div>
          Host has not started the brainstorming activity yet. Please wait.
        </div>
      )}
    </div>
  )
}

export default NotStarted
