import React, { useState } from "react"
import {
  FaThumbsUp,
  FaRegThumbsUp,
  FaThumbsDown,
  FaRegThumbsDown
} from "react-icons/fa"

const reviewInstructions = [
  "Review the ideas generated by other users, one at a time.",
  "Some of these ideas may have already been reviewed by other users and include their suggestions.",
  "You may choose to like or unlike the idea, add your suggestions to improve / extend the idea, and add or edit tags.",
  "Once you're done reviewing an idea, click on Next Idea to review the next idea."
]

const Review = ({
  userId,
  idea,
  moreIdeas,
  updateIdeaHandler,
  getNextIdea
}) => {
  const [like, setLike] = useState(false)
  const [unlike, setUnlike] = useState(false)
  const [tagsStr, setTagsStr] = useState(idea ? idea.tags.join(", ") : "")
  const [reviewStr, setReviewStr] = useState("")

  const nextButtonHandler = () => {
    /* Update the current Idea */
    const updatedIdea = {
      ...idea,
      likes: like ? idea.likes + 1 : idea.likes,
      unlikes: unlike ? idea.unlikes + 1 : idea.unlikes,
      tags: tagsStr === "" ? [] : tagsStr.split(/[\s,]+/),
      reviews:
        reviewStr === ""
          ? idea.reviews
          : idea.reviews.concat({ reviewer: userId, review: reviewStr })
    }
    updateIdeaHandler(updatedIdea)
    getNextIdea(userId)
  }

  return !idea ? (
    <div className="container">
      {moreIdeas ? (
        <h4>Waiting for other users to send ideas your way...</h4>
      ) : (
        <h4>
          You're done reviewing all the ideas. Wait for the moderator to start
          the Converge phase.
        </h4>
      )}
    </div>
  ) : (
    <div className="container">
      <h3>Review</h3>
      <hr />
      <div className="pt-5 p-4 mb-4" style={{ backgroundColor: "#eee" }}>
        <p className="lead">{idea.ideaContent}</p>
        {like ? (
          <FaThumbsUp
            className="text-primary"
            onClick={() => {
              setLike(!like)
            }}
          />
        ) : (
          <FaRegThumbsUp
            className="text-primary"
            onClick={() => {
              setLike(!like)
              setUnlike(false)
            }}
          />
        )}{" "}
        {unlike ? (
          <FaThumbsDown
            className="text-dark ml-1 mt-2"
            onClick={() => {
              setUnlike(!unlike)
            }}
          />
        ) : (
          <FaRegThumbsDown
            className="text-dark ml-1 mt-2"
            onClick={() => {
              setUnlike(!unlike)
              setLike(false)
            }}
          />
        )}
      </div>
      <div className="p-2">
        <h6>Tags</h6>
        <input
          className="mb-4"
          placeholder="tags..."
          value={tagsStr}
          onChange={(event) => {
            setTagsStr(event.target.value)
          }}
          onBlur={(event) => {
            setTagsStr(event.target.value.split(/[\s,]+/).join(", "))
          }}
        />
        <h4 className="text-danger">TODO: Previous comments should go here.</h4>
        <h6>How will you build on this idea?</h6>
        <textarea
          className="w-100 p-2 mb-2"
          placeholder="Your suggestion..."
          value={reviewStr}
          onChange={(event) => {
            setReviewStr(event.target.value)
          }}
        />
        <div className="text-right">
          <button
            type="button"
            className="btn btn-primary"
            onClick={() => nextButtonHandler()}
          >
            Next Idea
          </button>
        </div>
      </div>
    </div>
  )
}

export default Review
